### ISSUE TITLE
Missing JavaScript vars in base.mako

### ISSUE THREAD

**Issue by DavidJapan** [C-Pro/pgdocgen#1]
https://github.com/C-Pro/pgdocgen/blob/master/pgdocgen/templates/base.mako correctly defines content, sidebar and btn:
```
             content = document.getElementById("content");
             sidebar = document.getElementById("sidebar");
             btn = document.getElementById("btn");
```
but the base.mako file installed using PIP is wrong:
```
             var content = document.getElementById("content");
             var sidebarStyle = getComputedStyle(sidebar);
```
sidebar is not defined and, just as importantly, is not instantiated as an element with the ID "sidebar" so the public.html page rendered by the document generator process fails to display properly.

**Comment by C-Pro** [comment]
I have updated pip to latest version from master.
